import { Geist, Geist_Mono, Open_Sans, Inter, Playwrite_DK_Loopet } from "next/font/google";
import "../styles/globals.css";
import StoreProvider from "./StoreProvider";


const playwriteDKLoopet = Playwrite_DK_Loopet({
  variable: "--font-playwrite-DK-Loopet",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${inter.variable} ${playwriteDKLoopet.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
